---
name: Blocklist Manager

on:
  workflow_dispatch:
    inputs:
      name_to_delete:
        description: "Nom du centre à bloquer (copier-coller depuis VMD)"
        required: true
      zipcode_to_delete:
        description: "Code Postal du centre à bloquer (copier-coller depuis VMD)"
        required: true
      delete_reason:
        description: "Raison du blocage (facultatif)"
      git_issue:
        description: "Lien de l'issue Git correspondante (facultatif)"
        
  repository_dispatch:
    types:
      - webhook
jobs:

  scrape:
    name: "Blocklist Manager"
    runs-on: "ubuntu-20.04"
    steps:
      - uses: "actions/checkout@v2"
        with:
            token: ${{ secrets.PAT_GRZ }}
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.8"
      - name: "Install"
        run: make install
      - name: "Blocklist Manager..."
        run: make blocklistmanager
        env:
          INPUT_NAME_TO_DELETE: ${{ github.event.inputs.name_to_delete }}
          INPUT_GIT_ISSUE: ${{ github.event.inputs.git_issue }}
          INPUT_DELETE_REASON: ${{ github.event.inputs.delete_reason }}
          INPUT_ZIPCODE_TO_DELETE: ${{ github.event.inputs.zipcode_to_delete }}
      - name: "Copy output file"
        run: cp data/input/centers_blocklist.json .
      - name: "Get folder from main"
        run: |
          mkdir tmp2
          git clone --branch main https://github.com/CovidTrackerFr/vitemadose.git tmp2/
          cp -R tmp2/data/input/* data/input
          rm -rf tmp2/
          cp centers_blocklist.json data/input
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Blocklist - Ajout d'un centre
          push_options: '--force HEAD:main'
