name: OpenVPN
on:
  workflow_dispatch:
jobs:
  connect-open-vpn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Open VPN and config files
        env: 
          VPN_CONFIG: ${{ secrets.VPN_CONFIG }}
          VPN_CONNECT: ${{ secrets.VPN_CONNECT }}
        run: |
              sudo apt-get install openvpn
              mkdir ~/.ssh
              pwd
              ls
              sudo echo "$VPN_CONFIG" >> config.ovpn
              sudo echo "$VPN_CONNECT" >> auth.txt
      - name: ShowIP before
        run: |
              wget https://ipecho.net/plain -O - -q ; echo
              sudo ifconfig 
      - name: Connect VPN
        run: sudo openvpn --config config.ovpn --auth-user-pass auth.txt --daemon
      - name: Check VPN
        run: |
              sleep 30
              echo ${{ steps.connect_vpn.outputs.STATUS }}
              wget https://ipecho.net/plain -O - -q ; echo
              sudo ifconfig 
