name: Test

on:
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: "Test"
    runs-on: "ubuntu-20.04"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.8"
      - name: "Install dependencies"
        run: scripts/install
      - name: "Run tests"
        run: scripts/test
      - name: "List all contributors"
        run: scripts/contributors
      - name: "Install coverage badge"
        run: pip install pytest coverage coverage-badge
      - name: "Generate coverage badge"
        run: coverage-badge
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
